---
name: 🎨 Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/frontend.yml
      - scripts/fetch-frontend.sh

permissions: {}

concurrency:
  group: frontend

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # GOV.UK Frontend
          # - frontend: govuk-frontend
          #   version: v5.9.0
          # - frontend: govuk-frontend
          #   version: v5.10.0
          # MoJ Frontend
          # - frontend: moj-frontend
          #   version: v5.1.2
          - frontend: moj-frontend
            version: v5.1.3
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@f24d7193d98baebaeacc7e2227925dd47cc267f5 # v4.2.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Fetch Frontend
        id: fetch_frontend
        env:
          FRONTEND: ${{ matrix.frontend }}
          FRONTEND_VERSION: ${{ matrix.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/fetch-frontend.sh "${FRONTEND}" "${FRONTEND_VERSION}"

      - name: Deploy Frontend
        id: deploy_frontend
        env:
          FRONTEND: ${{ matrix.frontend }}
          FRONTEND_VERSION: ${{ matrix.version }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync "dist/${FRONTEND}/${FRONTEND_VERSION}" "s3://${S3_BUCKET}/${FRONTEND}/${FRONTEND_VERSION}" --delete
