---
name: 🎨 Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/frontend.yml
      - scripts/fetch-frontend.sh
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: frontend

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Generate Matrix
        id: generate_matrix
        run: |
          export MATRIX=$(jq -c . < ./config/frontend.json)
          echo "matrix=${MATRIX}" >>"${GITHUB_OUTPUT}"

  frontend-test:
    if: github.ref != 'refs/heads/main'
    needs: generate-matrix
    name: Frontend Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Fetch Frontend
        id: fetch_frontend
        env:
          FRONTEND: ${{ matrix.frontend }}
          FRONTEND_VERSION: ${{ matrix.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/fetch-frontend.sh "${FRONTEND}" "${FRONTEND_VERSION}"

  frontend-deploy:
    # if: github.ref == 'refs/heads/main'
    needs: generate-matrix
    name: Frontend Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: production
      url: ${{ steps.get_cloudfront_url.outputs.cloudfront-url }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Get CloudFront URL
        id: get_cloudfront_url
        env:
          CLOUDFRONT_URL: ${{ env.CLOUDFRONT_URL }}
        run: |
          echo "cloudfront-url=${CLOUDFRONT_URL}" >>"${GITHUB_OUTPUT}"

      - name: Fetch Frontend
        id: fetch_frontend
        env:
          FRONTEND: ${{ matrix.frontend }}
          FRONTEND_VERSION: ${{ matrix.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/fetch-frontend.sh "${FRONTEND}" "${FRONTEND_VERSION}"

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@f24d7193d98baebaeacc7e2227925dd47cc267f5 # v4.2.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Deploy Frontend
        id: deploy_frontend
        env:
          FRONTEND: ${{ matrix.frontend }}
          FRONTEND_VERSION: ${{ matrix.version }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync "dist/${FRONTEND}/${FRONTEND_VERSION}" "s3://${S3_BUCKET}/${FRONTEND}/${FRONTEND_VERSION}" --delete
