---
name: 🎨 Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/frontend.yml
      - scripts/fetch-frontend.sh

permissions: {}

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          # GOV.UK Frontend
          - frontend: govuk-frontend
            version: v5.9.0
          - frontend: govuk-frontend
            version: v5.10.0
          # MoJ Frontend
          - frontend: moj-frontend
            version: v5.1.2
          - frontend: moj-frontend
            version: v5.1.3
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Fetch Frontend
        id: fetch_frontend
        env:
          FRONTEND: ${{ matrix.frontend }}
          FRONTEND_VERSION: ${{ matrix.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/fetch-frontend.sh "${FRONTEND}" "${FRONTEND_VERSION}"
